[package]
name = "ssbh_editor"
version = "0.6.1"
authors = ["SMG"]
edition = "2021"
description = "View, edit, and validate models for Smash Ultimate"

[dependencies]
chrono = "0.4"
pollster = "0.2"
egui = { version = "0.19.0", default-features = false }
egui-wgpu = "0.19.0"
egui-winit = "0.19.0"
wgpu = "0.13.1"
winit = "0.27.2"
glam = { version = "0.20.2", features = ["mint", "bytemuck"] }
rfd = "0.10.0"
ssbh_wgpu = { git = "https://github.com/ScanMountGoat/ssbh_wgpu" }
nutexb_wgpu = { git = "https://github.com/ScanMountGoat/ssbh_wgpu" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features = ["strum", "serde"] }
strum = "0.24.1"
nutexb = "0.6.0"
octocrab = "0.16.0"
tokio = { version = "1", features = ["rt"] }
open = "2.1.3"
log = "0.4.17"
serde_json = "1.0"
strip-ansi-escapes = "0.1.1"
image = "0.24.2"
directories = "4.0"
once_cell = "1.13.0"
serde = { version = "1.0", features = ["derive"] }
xmltree = "0.10.3"
anyhow = "1.0"
thiserror = "1.0"
futures-intrusive = "0.4.0" # TODO: Avoid these dependencies?
futures = "0.3"

[profile.release]
strip = "debuginfo"
lto = true

[package.metadata.bundle]
icon = ["src/icons/SsbhEditor512_mac.png"]