[package]
name = "ssbh_editor"
version = "0.4.1"
authors = ["SMG"]
edition = "2021"

[dependencies]
chrono = "0.4"
pollster = "0.2"
egui = { git = "https://github.com/emilk/egui", default-features = false }
egui-wgpu = { git = "https://github.com/emilk/egui" }
egui-winit = { git = "https://github.com/emilk/egui" }
wgpu = "0.13.1"
winit = "0.26"
glam = { version = "0.20.2", features = ["mint", "bytemuck"] }
rfd = "0.9.0"
ssbh_wgpu = { git = "https://github.com/ScanMountGoat/ssbh_wgpu" }
nutexb_wgpu = { git = "https://github.com/ScanMountGoat/ssbh_wgpu" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features = ["strum", "serde"] }
strum = "0.24.1"
nutexb = "0.6.0"
octocrab = "0.16.0"
tokio = { version = "1", features = ["rt"] }
open = "2.1.3"
log = "0.4.17"
lazy_static = "1.4.0"
serde_json = "1.0.81"
strip-ansi-escapes = "0.1.1"
image = "0.24.2"
directories = "4.0"
once_cell = "1.13.0"

[profile.release]
strip = "debuginfo"