[package]
name = "ssbh_editor"
version = "0.1.0"
authors = ["SMG"]
edition = "2021"

[dependencies]
egui_wgpu_backend = "0.17.0"
chrono = "0.4"
pollster = "0.2"
egui = "0.17"
epi = "0.17"
egui_winit_platform = "0.14"
wgpu = "0.12"
winit = "0.26"
glam = { version = "0.20.2", features = ["mint", "bytemuck"] }
rfd = "0.7.0"
ssbh_wgpu = { git = "https://github.com/ScanMountGoat/ssbh_wgpu" }
nutexb_wgpu = { git = "https://github.com/ScanMountGoat/ssbh_wgpu" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features = ["strum1"] }
strum = "0.23.0"
nutexb = "0.6.0"
octocrab = "0.16.0"
tokio = { version = "1", features = ["rt"] }
open = "2.1.3"
log = "0.4.17"
lazy_static = "1.4.0"